# Existing citations overrides (for mapping local images or overriding fields)
- id: doi:10.1007/978-3-032-04981-0_15
  image: /images/Diff-RRG Longitudinal Disease-Wise Patch Difference as Guidance for LLM-Based Radiology Report Generation.png

- id: doi:10.1145/3746252.3761300
  image: /images/Quantized Factor Identifiable Causal Effect Variational Autoencoder.png

- id: doi:10.1016/j.neuroimage.2025.121077
  image: /images/A quantitatively interpretable model for Alzheimer’s disease prediction using.jpg

- id: doi:10.1007/978-981-97-8702-9_18
  image: /images/Prototype-Guided Contrastive Knowledge Graph Representation Learning for Diagnosis Prediction.png

- id: doi:10.1109/TNNLS.2023.3311195
  image: /images/Site-Invariant Meta-Modulation Learning for Multisite Autism Spectrum Disorders Diagnosis.gif

- id: doi:10.1109/TMI.2023.3337074
  image: /images/A Learnable Counter-Condition Analysis Framework for Functional Connectivity-Based Neurological Disorder Diagnosis.gif

- id: doi:10.1109/TMI.2023.3337362
  image: /images/EAG-RS A Novel Explainability-Guided ROI-Selection Framework for ASD Diagnosis via Inter-Regional Relation Learning.gif

- id: doi:10.1007/978-3-031-72069-7_6
  image: /images/BrainWaveNet Wavelet-Based Transformer for Autism Spectrum Disorder Diagnosis.jpg
  publisher: Medical Image Computing and Computer Assisted Intervention – MICCAI 2024. MICCAI 2024. Lecture Notes in Computer Science
  date: '2024-10-01'

- id: doi:10.1109/TMI.2025.3631105
  image: /images/Explainable Normative Modeling for Brain.png

- id: doi:10.1038/s41598-024-71309-2
  image: /images/Neurodevelopmental imprints of sociomarkers in adolescent brain connectomes.webp

- id: doi:10.1038/s41598-023-45796-8
  image: /images/Module of Axis-based Nexus Attention for weakly supervised object localization.webp

- id: doi:10.1016/j.psychres.2022.114871
  image: /images/Altered functional connectivity in psychotic disorder not otherwise specified.jpg

- id: doi:10.1016/j.neuroimage.2021.118048
  image: /images/A unified framework for personalized regions selection and functional relation modeling for early MCI identification.jpg

- id: doi:10.1109/ICASSP48485.2024.10448019
  image: /images/Eigendecomposition-Based Spatial-Temporal Attention for Brain Cognitive States Identification.gif

- id: doi:10.1007/978-3-031-16437-8_32
  image: /images/Prototype Learning of Inter-network Connectivity for ASD Diagnosis and Personalized Analysis.png

- id: doi:10.1007/978-3-030-87240-3_48
  image: /images/Meta-modulation Network for Domain Generalization in Multi-site fMRI Classification git.png
